# Generated by Django 4.2.3 on 2023-09-04 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card_search', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='color',
            name='card',
        ),
        migrations.AddField(
            model_name='color',
            name='card',
            field=models.ManyToManyField(related_name='colors', to='card_search.card'),
        ),
    ]
